server:
  port: 12345
apiPath: api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql
    url: jdbc:mysql://${spring.datasource.host}:3306/sirui?serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
    host: redis
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 解决springboot和swagger2版本冲突

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0


